[package]
edition = "2024"
name = "complete_graph"
publish = false
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-graphql = { workspace = true, features = ["dataloader"] }
axum = { workspace = true }
bots = { path = "../bots", default-features = false, features = ["ports"] }
email = { path = "../email", default-features = false, features = [
  "axum",
  "inbound",
  "ports",
] }
entity_access = { path = "../entity_access", default-features = false, features = [
  "inbound",
] }
entity_mutation = { path = "../entity_mutation" }
favorites = { path = "../favorites", default-features = false, features = ["ports"] }
graphql_activity = { path = "../graphql_activity" }
graphql_channel = { path = "../graphql_channel" }
graphql_common = { path = "../graphql_common" }
graphql_email = { path = "../graphql_email" }
graphql_entity_mutation = { path = "../graphql_entity_mutation" }
graphql_favorite = { path = "../graphql_favorite" }
graphql_notification = { path = "../graphql_notification" }
graphql_permission = { path = "../graphql_permission" }
graphql_properties = { path = "../graphql_properties" }
graphql_soup = { path = "../graphql_soup" }
macro_authorization = { path = "../macro_authorization", features = [
  "axum",
  "outbound",
] }
macro_user_id = { path = "../macro_user_id" }
model-entity = { path = "../model-entity" }
model_notifications = { path = "../model_notifications" }
notification = { path = "../notification" }
predicate-index = { path = "../predicate_index" }
soup = { path = "../soup", default-features = false, features = ["ports"] }
soup-filter-projection = { path = "../soup_filter_projection", default-features = false }
soup_realtime = { path = "../soup_realtime", default-features = false, features = [
  "ports",
] }
tokio = { workspace = true }
uuid = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
activity = { path = "../activity", default-features = false, features = ["realtime"] }
apollo-compiler = { workspace = true }
chrono = { workspace = true }
model_owner = { path = "../model_owner" }
model_user = { path = "../model_user" }
models_pagination = { path = "../models_pagination" }
models_properties = { path = "../models_properties" }
models_soup = { path = "../models_soup" }
rootcause = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
