[package]
edition = "2024"
name = "share_permission_db_utils"
publish = false
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
entity_access_db_utils = { path = "../entity_access_db_utils" }
macro_user_id = { path = "../macro_user_id" }
macro_uuid = { path = "../macro_uuid" }
model-entity = { path = "../model-entity" }
model_owner = { path = "../model_owner" }
models_permissions = { path = "../models_permissions" }
rootcause = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
macro_db_migrator = { path = "../macro_db_migrator" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
