[package]
edition = "2024"
name = "item_filters"
publish = false
version = "0.1.0"

[features]
default = ["native"]
mock = []
native = ["document_sub_type/default", "notification_state/postgres"]
schema = ["dep:schemars", "dep:utoipa", "notification_state/schema"]

[dependencies]
chrono = { workspace = true }
document_sub_type = { path = "../document_sub_type", default-features = false }
either = { workspace = true }
filter_ast = { path = "../filter_ast" }
macro_user_id = { path = "../macro_user_id" }
model_file_type = { path = "../model_file_type" }
model_owner = { path = "../model_owner" }
nom = { workspace = true }
non_empty = { path = "../non_empty" }
notification_state = { path = "../notification_state" }
rootcause = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, features = ["rc"] }
serde_json = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
utoipa = { workspace = true, optional = true }
uuid = { workspace = true }

[dev-dependencies]
cool_asserts = "2.0.3"
