[package]
edition = "2024"
name = "models_soup"
publish = false
version = "0.1.0"

[features]
mock = []
schema = ["dep:utoipa", "item_filters/schema"]

[dependencies]
anyhow = { workspace = true }
call = { path = "../call", default-features = false }
channels = { path = "../channels", default-features = false, features = ["list"] }
chrono = { workspace = true }
crm = { path = "../crm", default-features = false }
document_sub_type = { path = "../document_sub_type" }
doppleganger = { workspace = true, features = ["chrono", "uuid"] }
email = { path = "../email" }
item_filters = { path = "../item_filters" }
macro_user_id = { path = "../macro_user_id" }
model = { path = "../model" }
model-entity = { path = "../model-entity" }
model_owner = { path = "../model_owner" }
models_pagination = { path = "../models_pagination" }
models_properties = { path = "../models_properties" }
reminders = { path = "../reminders", default-features = false }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
utoipa = { workspace = true, optional = true }
uuid = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
