[package]
name = "initiative_documents"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
documents_hex = { package = "documents", path = "../documents", default-features = false, features = ["document_create"] }
initiative = { path = "../initiative", default-features = false, features = ["ports"] }
rootcause = { workspace = true }
tracing = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
