[package]
edition = "2024"
name = "graphql_common"
publish = false
version = "0.1.0"

[dependencies]
async-graphql = { workspace = true, features = ["dataloader"] }
axum = { workspace = true }
axum-extra = { workspace = true }
filter_ast = { path = "../filter_ast" }
item_filters = { path = "../item_filters" }
macro_authorization = { path = "../macro_authorization", default-features = false, features = [
  "axum",
] }
macro_user_id = { path = "../macro_user_id" }
model-entity = { path = "../model-entity" }
model_owner = { path = "../model_owner" }
models_properties = { path = "../models_properties" }
rootcause = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
model_user = { path = "../model_user" }
rootcause = { workspace = true }
