[package]
edition = "2024"
name = "model_owner"
publish = false
version = "0.1.0"

[features]
sqlx = ["dep:sqlx"]

[dependencies]
bot_id = { path = "../bot_id" }
macro_user_id = { path = "../macro_user_id" }
serde = { workspace = true }
sqlx = { workspace = true, optional = true }
thiserror = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
