[package]
edition = "2024"
name = "initiative"
publish = false
version = "0.1.0"

[features]
default = ["ports", "postgres"]
inbound = [
  "dep:axum",
  "dep:macro_authorization",
  "dep:model-error-response",
  "dep:utoipa",
  "entity_access/inbound",
  "ports",
]
outbound = ["ports"]
resources = ["outbound", "dep:properties", "dep:system_properties", "dep:models_properties"]
ports = ["dep:entity_access", "dep:tracing"]
postgres = [
  "dep:sqlx",
  "dep:entity_access_db_utils",
  "dep:share_permission_db_utils",
  "dep:model-entity",
  "dep:macro_uuid",
  "outbound",
]

[dependencies]
properties = { path = "../properties", optional = true, default-features = false }
system_properties = { path = "../system_properties", optional = true }
models_properties = { path = "../models_properties", optional = true }
activity = { path = "../activity", default-features = false }
axum = { workspace = true, optional = true }
chrono = { workspace = true, features = ["serde"] }
entity_access = { path = "../entity_access", optional = true, default-features = false, features = ["ports"] }
entity_access_db_utils = { path = "../entity_access_db_utils", optional = true }
macro_authorization = { path = "../macro_authorization", optional = true, default-features = false, features = ["axum"] }
macro_event_broker = { path = "../macro_event_broker", default-features = false }
macro_event_topics = { path = "../macro_event_topics" }
macro_user_id = { path = "../macro_user_id" }
macro_uuid = { path = "../macro_uuid", optional = true }
model-entity = { path = "../model-entity", optional = true }
model-error-response = { path = "../model-error-response", optional = true }
models_permissions = { path = "../models_permissions" }
rootcause = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
share_permission_db_utils = { path = "../share_permission_db_utils", optional = true }
sqlx = { workspace = true, optional = true }
thiserror = { workspace = true }
tracing = { workspace = true, optional = true }
unicode-segmentation = { workspace = true }
utoipa = { workspace = true, optional = true }
uuid = { workspace = true, features = ["serde", "v7"] }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
mockall = { workspace = true }

[dev-dependencies]
activity = { path = "../activity", default-features = false, features = ["outbound"] }
entity_access = { path = "../entity_access", default-features = false, features = ["outbound"] }
anyhow = { workspace = true }
http-body-util = { workspace = true }
macro_db_migrator = { path = "../macro_db_migrator" }
model_user = { path = "../model_user" }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tower = { workspace = true }
